// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace fastbuildvsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "fastbuildvsix.ff0d2124-3e2e-4df1-92ea-b1ec83fb6678";
        public const string Name = "fastbuildvsix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
