// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace fastbuildvsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string fastbuildvsixString = "0d419937-82de-4fee-b11a-8e50a5a2fcd4";
        public static Guid fastbuildvsix = new Guid(fastbuildvsixString);

        public const string guidfastbuildvsixPackageCmdSetString = "62489d4f-e98e-474b-a11c-2adce89fd0f1";
        public static Guid guidfastbuildvsixPackageCmdSet = new Guid(guidfastbuildvsixPackageCmdSetString);

        public const string guidImages1String = "f20a84db-55f5-4851-9b92-a862e75d3b04";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyMenuGroup1 = 0x1021;
        public const int FASTBuildId = 0x0100;
        public const int SlnFASTBuildId = 0x0101;
        public const int ProjContextMenuGroup = 0x1080;
        public const int ContextMenuFASTBuildId = 0x0102;
        public const int ContextMenuFASTBuildProjectId = 0x0109;
        public const int SlnContextMenuGroup = 0x1081;
        public const int SlnContextMenuFASTBuildId = 0x0103;
        public const int FASTBuildMonitorCommandId = 0x0104;
        public const int FASTBuildMonitorToolsCommandId = 0x0105;
        public const int ContextMenuFASTBuildClearId = 0x0106;
        public const int SlnContextMenuFASTBuildClearId = 0x0107;
        public const int SlnMenuFASTBuildClearId = 0x0110;
        public const int CancelFASTBuild = 0x0108;
        public const int cmdidToolWindow1Command = 0x1082;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}